// Authentication Actions
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Accounts Actions
export const FETCH_ACCOUNTS_START = 'FETCH_ACCOUNTS_START';
export const FETCH_ACCOUNTS_FAIL = 'FETCH_ACCOUNTS_FAIL';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';

export const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_START';

// Banks Actions
export const FETCH_BANKS_START = 'FETCH_BANKS_START';
export const FETCH_BANKS_FAIL = 'FETCH_BANKS_FAIL';
export const FETCH_BANKS_SUCCESS = 'FETCH_BANKS_SUCCESS';